name: class_to_string
description: It allows to get beautiful class to string.
version: 1.1.0
homepage: https://github.com/BreX900/data_class/tree/main/class_to_string
repository: https://github.com/BreX900/data_class

environment:
  sdk: '>=3.0.0 <4.0.0'

scripts:
  publish: dart pub publish

dev_dependencies:
  mek_lints: ^2.0.0
  test: ^1.16.0
